### ISSUE TITLE
release build failing on CI-CD

### ISSUE THREAD

**Issue by DrFacepalm** [MatrixAI/TypeScript-Demo-Electron#4]
The error shown is:
```
error: a 'x86_64-linux' with features {kvm} is required to build '/nix/store/w1hs5f43r3rys1lbz93qyjqfg69j49vy-typescript-demo-electron-1.0.0-linux-x64.rpm.drv', but I am a 'x86_64-linux' with features {benchmark, big-parallel, nixos-test}
```

**Comment by CMCDragonkai** [comment]
Yea you might have to disable the rpm build. I don't think it's a big deal. Deb is more popular. And we have the other package formats too.

On 9 March 2021 7:49:18 pm AEDT, DrFacepalm <notifications@github.com> wrote:
>The error shown is:
>```
>error: a 'x86_64-linux' with features {kvm} is required to build
>'/nix/store/w1hs5f43r3rys1lbz93qyjqfg69j49vy-typescript-demo-electron-1.0.0-linux-x64.rpm.drv',
>but I am a 'x86_64-linux' with features {benchmark, big-parallel,
>nixos-test}
>```
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/MatrixAI/TypeScript-Demo-Electron/issues/4

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by CMCDragonkai** [comment]
Not building rpm via CI/CD. Will resolve this later. Also I was told that the expression will default on software emulation when possible. I'm pretty sure there's a way to deal with this in the future.
